# Generated by Django 4.1.5 on 2023-07-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tech')),
            ],
        ),
    ]
